import layerCatalog from '../config/layerCatalog.json';
import {
  buildEarthEngineGeometryExpression,
  buildAoiFromCoordinateRing,
  parseSerializedAoi,
} from '../utils/aoi';

const createYearlyHistoryExpression = () => (
  layerCatalog.basic.jrcYearlyHistory.sources.map((source) => (
    `ee.ImageCollection('${source.dataset}')\n    .filter(ee.Filter.calendarRange(${source.startYear}, ${source.endYear}, 'year')).select('waterClass')`
  )).reduce((expression, source, index) => (
    index === 0 ? source : `${expression}\n    .merge(${source})`
  ), '')
);

export const createCodeSnippet = (params, dataType) => {
  const catalog = layerCatalog.basic;
  const aoi =
    parseSerializedAoi(params.aoi) ||
    buildAoiFromCoordinateRing(JSON.parse(params.coordinates || '[]'));

  if (!aoi) {
    return '';
  }

  const geometryExpression = buildEarthEngineGeometryExpression(aoi);
  const historicalCatalog = catalog.historical;
  const hotspotCatalog = catalog.hotspot;
  const supplementaryCatalog = catalog.supplementary;

  let code = `// Google Earth Engine Code for ${dataType} Analysis
// Generated by SATGPT

// Define Area of Interest
var geometry = ${geometryExpression};
var AoI = ee.FeatureCollection(ee.Feature(geometry));

// Time parameters
var time_start = '${params.time_start}';
var time_end = '${params.time_end}';

`;

  if (dataType === 'historical') {
    code += `// Historical Water Analysis using JRC Surface Water
var start_year = parseInt(time_start.split("-")[0]);
var end_year = parseInt(time_end.split("-")[0]);

// Annual history through 2024, including corrected 2016-2021 classes.
var yearlyHistory = ${createYearlyHistoryExpression()};

var jrcSurfaceWater = yearlyHistory
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('${historicalCatalog.water.band}').eq(${historicalCatalog.water.matchValue}); })
    .sum()
    .clip(AoI);

var jrcSurfaceFlood = yearlyHistory
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('${historicalCatalog.flood.band}').eq(${historicalCatalog.flood.matchValue}); })
    .sum()
    .clip(AoI);

var LCLU = ee.ImageCollection('${supplementaryCatalog.landcover.dataset}').first().clip(AoI);
var PopulationDensity = ee.Image('${supplementaryCatalog.populationDensity.dataset}').clip(AoI);
PopulationDensity = PopulationDensity.visualize(${JSON.stringify(supplementaryCatalog.populationDensity.visualization)});
var SoilTexture = ee.Image('${supplementaryCatalog.soilTexture.dataset}').select('${supplementaryCatalog.soilTexture.band}').clip(AoI);
SoilTexture = SoilTexture.visualize(${JSON.stringify(supplementaryCatalog.soilTexture.visualization)});
var HealthCareAccess = ee.Image('${supplementaryCatalog.healthCareAccess.dataset}').select('${supplementaryCatalog.healthCareAccess.band}').clip(AoI);
HealthCareAccess = HealthCareAccess.visualize(${JSON.stringify(supplementaryCatalog.healthCareAccess.visualization)});

// Visualize
Map.centerObject(AoI, 10);
Map.addLayer(jrcSurfaceWater.updateMask(jrcSurfaceWater.gt(0)),
             ${JSON.stringify(historicalCatalog.water.visualization)}, 'Permanent Water');
Map.addLayer(jrcSurfaceFlood.updateMask(jrcSurfaceFlood.gt(0)),
             ${JSON.stringify(historicalCatalog.flood.visualization)}, 'Flood');
Map.addLayer(LCLU, {}, 'LCLU');
Map.addLayer(PopulationDensity, {}, 'Population Density');
Map.addLayer(SoilTexture, {}, 'Soil Texture');
Map.addLayer(HealthCareAccess, {}, 'Healthcare Access');
`;
  } else if (dataType === 'flood_hotspot') {
    code += `// Flood Hotspot Analysis
var year_from = ${params.year_start || params.year_from || 2000};
var year_to = ${params.year_end || null};
var year_count = ${params.year_count || 5};
year_to = year_to || (year_from + year_count - 1);
year_count = year_to - year_from + 1;

var WaterESA2 = ee.ImageCollection('${hotspotCatalog.worldCoverPrimaryWater.dataset}').first().eq(${hotspotCatalog.worldCoverPrimaryWater.classValue}).selfMask();
var WaterESA1 = ee.ImageCollection('${hotspotCatalog.worldCoverLegacyWater.dataset}').first().eq(${hotspotCatalog.worldCoverLegacyWater.classValue}).selfMask();
// Annual history through 2024, including corrected 2016-2021 classes.
var waterHistory = ${createYearlyHistoryExpression()}
    .filter(ee.Filter.calendarRange(year_from, year_to, 'year'));

var masks = waterHistory.map(function(image) {
    return image.select('waterClass').eq(3);
});

var PermanentWater = masks.sum();
var PermanentWaterFrequency = PermanentWater.divide(year_count);
var PermanentWaterFrequencyMap = PermanentWaterFrequency.gt(0).selfMask();
var PermanentWaterLayer = ee.ImageCollection([WaterESA1.rename('waterClass'), WaterESA2.rename('waterClass'), PermanentWaterFrequencyMap]).mosaic().clip(AoI);

var binary_masks = waterHistory.map(function(image) {
    return image.select('waterClass').eq(2);
});
var yearsWithWater = binary_masks.sum();
var floodFrequency = yearsWithWater.divide(year_count);
var floodFrequencyMap = floodFrequency.where(PermanentWaterLayer.eq(1), 0).selfMask().clip(AoI);
floodFrequencyMap = floodFrequencyMap.where(floodFrequencyMap.gt(0.9), 0.90);

var LCLU = ee.ImageCollection('${supplementaryCatalog.landcover.dataset}').first().clip(AoI);
var PopulationDensity = ee.Image('${supplementaryCatalog.populationDensity.dataset}').clip(AoI);
PopulationDensity = PopulationDensity.visualize(${JSON.stringify(supplementaryCatalog.populationDensity.visualization)});
var SoilTexture = ee.Image('${supplementaryCatalog.soilTexture.dataset}').select('${supplementaryCatalog.soilTexture.band}').clip(AoI);
SoilTexture = SoilTexture.visualize(${JSON.stringify(supplementaryCatalog.soilTexture.visualization)});
var HealthCareAccess = ee.Image('${supplementaryCatalog.healthCareAccess.dataset}').select('${supplementaryCatalog.healthCareAccess.band}').clip(AoI);
HealthCareAccess = HealthCareAccess.visualize(${JSON.stringify(supplementaryCatalog.healthCareAccess.visualization)});

Map.centerObject(AoI, 10);
Map.addLayer(PermanentWaterLayer, ${JSON.stringify(hotspotCatalog.water.visualization)}, 'Permanent Water');
Map.addLayer(floodFrequencyMap, ${JSON.stringify(hotspotCatalog.floodFrequency.visualization)}, 'Flood Frequency');
Map.addLayer(LCLU, {}, 'LCLU');
Map.addLayer(PopulationDensity, {}, 'Population Density');
Map.addLayer(SoilTexture, {}, 'Soil Texture');
Map.addLayer(HealthCareAccess, {}, 'Healthcare Access');
`;
  }

  return code;
};

export default createCodeSnippet;
