import layerCatalog from './layerCatalog.json';

export const AGENT_LAYER_SOURCE_REFERENCES = {
  sentinel1: {
    datasetId: 'COPERNICUS/S1_GRD',
    producer: 'European Union / ESA / Copernicus',
    resolution: '10m VV/VH bands; angle band is coarser',
    contentDate: 'From 2014-10-03; 6-day revisit in Earth Engine catalog',
    license: 'Copernicus Sentinel Data Terms and Conditions',
    overview: 'Sentinel-1 GRD is C-band SAR imagery processed by Earth Engine with thermal noise removal, radiometric calibration, terrain correction, and conversion to decibels. In this project it is the cloud-resistant evidence source for SAR context and flood change detection.',
    cautions: 'SAR backscatter is sensitive to surface roughness, incidence angle, vegetation, urban double bounce, and speckle. Read it together with AOI, date choice, and flood mask.',
    citation: 'Earth Engine Data Catalog: Sentinel-1 SAR GRD, European Union / ESA / Copernicus.',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S1_GRD',
  },
  sentinel2: {
    datasetId: 'COPERNICUS/S2_SR_HARMONIZED',
    producer: 'European Union / ESA / Copernicus',
    resolution: '10m, 20m, and 60m spectral bands; RGB uses 10m bands',
    contentDate: 'From 2017-03-28; 5-day revisit in Earth Engine catalog',
    license: 'Copernicus Sentinel Data Terms and Conditions',
    overview: 'Harmonized Sentinel-2 Level-2A Surface Reflectance provides optical multispectral imagery for land monitoring. In this project it is used as true-color visual context around the selected flood dates.',
    cautions: 'Optical imagery can be affected by cloud, haze, smoke, shadows, and water turbidity. It is evidence for visual interpretation, not a flood mask by itself.',
    citation: 'Earth Engine Data Catalog: Harmonized Sentinel-2 MSI Level-2A Surface Reflectance, European Union / ESA / Copernicus.',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED',
  },
  jrcGsw: {
    datasetId: 'JRC/GSW1_4/GlobalSurfaceWater',
    producer: 'EC JRC / Google',
    resolution: '30m Landsat-derived water history layers',
    contentDate: '1984-03-16 to 2022-01-01 in Earth Engine catalog',
    license: 'Copernicus Programme; free use with proper acknowledgement',
    overview: 'JRC Global Surface Water maps the location and temporal distribution of surface water from 1984 to 2021. In this project it helps separate permanent or historical water from possible new inundation.',
    cautions: 'It is a long-term Landsat-derived water history layer. It should not be treated as real-time flood observation.',
    citation: 'Pekel et al. 2016. High-resolution mapping of global surface water and its long-term changes. Nature 540, 418-422. doi:10.1038/nature20584.',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/JRC_GSW1_4_GlobalSurfaceWater',
  },
  jrcGswYearlyHistory: {
    datasetId: layerCatalog.basic.jrcYearlyHistory.sources.map((source) => source.dataset).join(' + '),
    producer: 'EC JRC / Google',
    resolution: '30m Landsat-derived yearly water classification',
    contentDate: '1984-2024; v1.4 for 1984-2015, corrected v1.5 for 2016-2021, v1.5 for 2022-2024',
    license: 'Copernicus Programme; free use with proper acknowledgement',
    overview: 'JRC Yearly Water Classification History stores annual surface-water classes. SatGPT uses class 3 as permanent water, class 2 as seasonal inundation, and multi-year frequency to identify inundation hotspots.',
    cautions: 'Annual data ends in 2024; use Flood Detection for 2025-2026 events. Seasonal water is not proof of a flood event. The Landsat Collection 1/2 transition can introduce spatial offsets from 2022 onward.',
    citation: 'Pekel et al. 2016. High-resolution mapping of global surface water and its long-term changes. Nature 540, 418-422. doi:10.1038/nature20584.',
    officialUrl: 'https://global-surface-water.appspot.com/download',
  },
  populationDensity: {
    datasetId: 'CIESIN/GPWv411/GPW_UNWPP-Adjusted_Population_Density',
    producer: 'NASA SEDAC / CIESIN, Columbia University',
    resolution: '30 arc-second grid, about 1km at the equator',
    contentDate: 'Modeled years 2000, 2005, 2010, 2015, 2020',
    license: 'CC-BY-4.0',
    overview: 'GPWv4.11 estimates population density using census and administrative-unit population inputs, adjusted to match the 2015 Revision of UN World Population Prospects country totals. In SatGPT it is exposure context, not a damage estimate.',
    cautions: 'Population is allocated from administrative source units to grid cells. Local settlement detail may be smoothed, especially where census units are large.',
    citation: 'CIESIN, Columbia University. 2018. GPWv4.11 Population Density Adjusted to Match 2015 Revision of UN WPP Country Totals. NASA SEDAC. doi:10.7927/H4F47M65.',
    doi: 'https://doi.org/10.7927/H4F47M65',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/CIESIN_GPWv411_GPW_UNWPP-Adjusted_Population_Density',
  },
  lclu: {
    datasetId: 'ESA/WorldCover/v200',
    producer: 'ESA WorldCover Consortium',
    resolution: '10m',
    contentDate: '2021-01-01 to 2022-01-01 in Earth Engine catalog',
    license: 'CC-BY-4.0',
    overview: 'ESA WorldCover 10m v200 provides a global 2021 land cover map derived from Sentinel-1 and Sentinel-2 data. It contains 11 land cover classes and is used here to interpret flooded land-cover context.',
    cautions: 'WorldCover is a categorical land-cover product. It helps describe affected surface types, but direct damage conclusions still require flood mask quality checks and local validation.',
    citation: 'Zanaga et al. 2022. ESA WorldCover 10 m 2021 v200. doi:10.5281/zenodo.7254221.',
    doi: 'https://doi.org/10.5281/zenodo.7254221',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/ESA_WorldCover_v200',
  },
  soilTexture: {
    datasetId: 'OpenLandMap/SOL/SOL_TEXTURE-CLASS_USDA-TT_M/v02',
    producer: 'EnvirometriX Ltd / OpenLandMap',
    resolution: '250m',
    contentDate: '1950-01-01 to 2018-01-01 in Earth Engine catalog',
    license: 'CC-BY-SA-4.0',
    overview: 'OpenLandMap soil texture classes follow the USDA system for six soil depths from 0 to 200cm. SatGPT currently uses the 10cm band as hydrologic context around the AOI.',
    cautions: 'This is a modeled global soil product. It is useful for regional infiltration/runoff context, but not a substitute for field soil surveys or engineering-scale soil data.',
    citation: 'Hengl, T. 2018. Soil texture classes (USDA system) for 6 soil depths at 250 m, Version v02. Zenodo. doi:10.5281/zenodo.1475451.',
    doi: 'https://doi.org/10.5281/zenodo.1475451',
    officialUrl: 'https://developers.google.com/earth-engine/datasets/catalog/OpenLandMap_SOL_SOL_TEXTURE-CLASS_USDA-TT_M_v02',
  },
};

export default AGENT_LAYER_SOURCE_REFERENCES;
